### ISSUE TITLE
`wl status` does not work

### ISSUE THREAD

**Issue by bufm** [dotcs/worklog#12]
```
wl status
Traceback (most recent call last):
  File "/opt/anaconda3/envs/worklog/bin/wl", line 8, in <module>
    sys.exit(run())
  File "/opt/anaconda3/envs/worklog/lib/python3.7/site-packages/worklog/__init__.py", line 46, in run
    dispatch(log, parser, cli_args, cfg)
  File "/opt/anaconda3/envs/worklog/lib/python3.7/site-packages/worklog/dispatcher.py", line 52, in dispatch
    log.status(hours_target, hours_max, query_date=query_date, fmt=fmt)
  File "/opt/anaconda3/envs/worklog/lib/python3.7/site-packages/worklog/log.py", line 256, in status
    + "]",
  File "/opt/anaconda3/envs/worklog/lib/python3.7/site-packages/worklog/log.py", line 253, in <listcomp>
    for k, v in all_touched_tasks.items()
  File "/opt/anaconda3/envs/worklog/lib/python3.7/site-packages/worklog/utils/formatting.py", line 16, in format_timedelta
    raise ValueError("value must be either a Python or a numpy timedelta instance")
ValueError: value must be either a Python or a numpy timedelta instance
```

**Comment by dotcs** [comment]
This is fixed by #13.
