### ISSUE TITLE
`wl report` broken when never having used tasks

### ISSUE THREAD

**Issue by eklenske** [dotcs/worklog#18]
Currently I just use the worklog for simple time tracking (`wl session start`, `wl session stop`). I'm not using fine-grained task tracking.

When I try to get a report (`wl report`), I get the following error:

```
Traceback (most recent call last):
  File "/home/edgar/.local/bin/wl", line 8, in <module>
    sys.exit(run())
  File "/home/edgar/.local/lib/python3.8/site-packages/worklog/__init__.py", line 53, in run
    dispatch(log, parser, cli_args, cfg)
  File "/home/edgar/.local/lib/python3.8/site-packages/worklog/dispatcher.py", line 65, in dispatch
    log.report(cli_args.date_from, cli_args.date_to)
  File "/home/edgar/.local/lib/python3.8/site-packages/worklog/log.py", line 168, in report
    df_tasks = self._aggregate_tasks(time_mask & task_mask)
  File "/home/edgar/.local/lib/python3.8/site-packages/worklog/log.py", line 560, in _aggregate_tasks
    df.set_index(wc.COL_LOG_DATETIME)
  File "/home/edgar/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 4550, in set_index
    raise KeyError(f"None of {missing} are in the columns")
```

As soon as I start some task (`wl task start something`), the report works.

**Comment by dotcs** [comment]
Thanks Edgar and nice to see that you use worklog for keeping track of your work. Appreciate it!
This issue has been fixed as a side-effect of #19 and the latest release ([0.0.36](https://github.com/dotcs/worklog/releases/tag/0.0.36)). Please re-open in case you have still problems.
