### ISSUE TITLE
`wl report` does not work when `.worklog` is empty

### ISSUE THREAD

**Issue by eklenske** [dotcs/worklog#20]
In a new installation without having a `.worklog` (or an empty one), I get the following error:

```
user@host: ~ $ wl report
Traceback (most recent call last):
  File "/home/user/.local/bin/wl", line 8, in <module>
    sys.exit(run())
  File "/home/user/.local/lib/python3.8/site-packages/worklog/__init__.py", line 53, in run
    dispatch(log, parser, cli_args, cfg)
  File "/home/user/.local/lib/python3.8/site-packages/worklog/dispatcher.py", line 65, in dispatch
    log.report(cli_args.date_from, cli_args.date_to)
  File "/home/user/.local/lib/python3.8/site-packages/worklog/log.py", line 151, in report
    df_day = self._aggregate_time(time_mask & session_mask, resample="D")
  File "/home/user/.local/lib/python3.8/site-packages/worklog/log.py", line 553, in _aggregate_time
    df.set_index(wc.COL_LOG_DATETIME)
  File "/home/user/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 8074, in resample
    return get_resampler(
  File "/home/user/.local/lib/python3.8/site-packages/pandas/core/resample.py", line 1269, in get_resampler
    return tg._get_resampler(obj, kind=kind)
  File "/home/user/.local/lib/python3.8/site-packages/pandas/core/resample.py", line 1434, in _get_resampler
    raise TypeError(
TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'
```

**Comment by dotcs** [comment]
Thanks for reporting. This issue has been fixed in the latest release.

**Comment by eklenske** [comment]
Thanks for fixing!
